version: '3.8'

services:
  vigil-analyse:
    build: .
    container_name: vigil-analyse
    ports:
      - "3001:3001"
    volumes:
      - D:\\Program IT\\docker_data\\VigilAnalyse_data:/app/data
    restart: always
